### ISSUE TITLE
Learner logins.sql Code Review

### ISSUE THREAD

**Issue by bradley-pearson6597** [pradgade/Learner-Logins---Active-users#1]
Hey @pradgade,

I have reviewed your SQL code `Learner logins.sql` and had a few thoughts about it:

- I really like what you've done here  `DATE_FORMAT(played_date, '%Y-%m-01'`. A simple way of forcing all the dates to be the first of the month but I haven't thought of it like this before.
- Could be useful to have a comment about what the different type ids mean. I did see that they are in the table comments just could be useful for a quick glance over the code.
- Spelling has an app type of 0 and 1 depending on whether it's web or mobile. Could this be an issue.
- Could it be worth giving the web app data a unique app_type rather than 0. Maybe negative numbers?
- Very easy to follow and I managed to run it myself using temporary tables and ran as expected :)

If you have any questions about anything here please let me know :)

**Comment by pradgade** [comment]
Hey @bradley-pearson6597,

Thank you for reviewing my code.

I will add the comment regarding the type ids. The type is just an identifier for all mobile apps, There are no type ids for web apps, hence I chose to randomly put them as 0. Yes, I can update them as unique ones instead of 0 that will be more clear. 

Glad you found my code easy to follow :)
